package animatscaninos.interfaz;

/*
 * Interfase.java
 *
 * Created on 21 de marzo de 2008, 05:05 PM
 */



/**
 *
 * @author  Diego Enrique Hernández González
 * 
 */

import animatscaninos.agentes.Mundo;


public class Interfase extends javax.swing.JFrame {
    
    /** Creates new form Interfase */
    public Interfase() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearAnimat = new javax.swing.JButton();
        jButtonMatarAnimat = new javax.swing.JButton();
        jButtonPonerAlimento = new javax.swing.JButton();
        jButtonQuitarAlimento = new javax.swing.JButton();
        jButtonPonerAgua = new javax.swing.JButton();
        jButtonQuitarAgua = new javax.swing.JButton();
        jPanelSensores = new javax.swing.JPanel();
        jLabelSensorAlimento = new javax.swing.JLabel();
        jLabelSensorAgua = new javax.swing.JLabel();
        jLabelSensorAlmohada = new javax.swing.JLabel();
        jLabelSensorTerritorio = new javax.swing.JLabel();
        jLabelSensorPerro = new javax.swing.JLabel();
        jLabelSensorAgresion = new javax.swing.JLabel();
        jButtonMostrarAnimat = new javax.swing.JButton();
        jPanelActivacion = new javax.swing.JPanel();
        jLabelActivacionIrPorComida = new javax.swing.JLabel();
        jLabelActivacionComer = new javax.swing.JLabel();
        jLabelActivacionIrPorAgua = new javax.swing.JLabel();
        jLabelActivacionBeber = new javax.swing.JLabel();
        jLabelActivacionHusmear = new javax.swing.JLabel();
        jLabelActivacionMarcarTerritorio = new javax.swing.JLabel();
        jLabelActivacionEvacuar = new javax.swing.JLabel();
        jLabelActivacionirADormir = new javax.swing.JLabel();
        jLabelActivacionDormir = new javax.swing.JLabel();
        jLabelActivacionLadrar = new javax.swing.JLabel();
        jLabelActivacionPelear = new javax.swing.JLabel();
        jLabelActivacionHuir = new javax.swing.JLabel();
        jPanelMotivaciones = new javax.swing.JPanel();
        jLabelMotivacionHambre = new javax.swing.JLabel();
        jLabelMotivacionSed = new javax.swing.JLabel();
        jLabelMotivacionCuriosidad = new javax.swing.JLabel();
        jLabelMotivacionExpansion = new javax.swing.JLabel();
        jLabelMotivacionIncontinencia = new javax.swing.JLabel();
        jLabelMotivacionCansancio = new javax.swing.JLabel();
        jLabelMotivacionIra = new javax.swing.JLabel();
        jLabelMotivacionMiedo = new javax.swing.JLabel();
        jPanelMundo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCrearAnimat.setText("CrearAnimat");
        jButtonCrearAnimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAnimatActionPerformed(evt);
            }
        });

        jButtonMatarAnimat.setText("Matar Animat");
        jButtonMatarAnimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatarAnimatActionPerformed(evt);
            }
        });

        jButtonPonerAlimento.setText("Poner Alimento");
        jButtonPonerAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPonerAlimentoActionPerformed(evt);
            }
        });

        jButtonQuitarAlimento.setText("Quitar Alimento");
        jButtonQuitarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarAlimentoActionPerformed(evt);
            }
        });

        jButtonPonerAgua.setText("Poner Agua");
        jButtonPonerAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPonerAguaActionPerformed(evt);
            }
        });

        jButtonQuitarAgua.setText("Quitar Agua");
        jButtonQuitarAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarAguaActionPerformed(evt);
            }
        });

        jPanelSensores.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensores"));

        jLabelSensorAlimento.setText("Alimento al alcance:");

        jLabelSensorAgua.setText("Agua al alcance:");

        jLabelSensorAlmohada.setText("Almohada al alcance:");

        jLabelSensorTerritorio.setText("Territorio ajeno:");

        jLabelSensorPerro.setText("Perro al alcance:");

        jLabelSensorAgresion.setText("Agresion:");

        javax.swing.GroupLayout jPanelSensoresLayout = new javax.swing.GroupLayout(jPanelSensores);
        jPanelSensores.setLayout(jPanelSensoresLayout);
        jPanelSensoresLayout.setHorizontalGroup(
            jPanelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSensoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSensorAlimento)
                    .addComponent(jLabelSensorAgua)
                    .addComponent(jLabelSensorAlmohada)
                    .addComponent(jLabelSensorTerritorio)
                    .addComponent(jLabelSensorPerro)
                    .addComponent(jLabelSensorAgresion))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelSensoresLayout.setVerticalGroup(
            jPanelSensoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSensoresLayout.createSequentialGroup()
                .addComponent(jLabelSensorAlimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSensorAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSensorAlmohada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSensorTerritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSensorPerro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSensorAgresion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonMostrarAnimat.setText("Mostrar Animat");
        jButtonMostrarAnimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarAnimatActionPerformed(evt);
            }
        });

        jPanelActivacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel de Activación"));

        jLabelActivacionIrPorComida.setText("Ir por comida:");

        jLabelActivacionComer.setText("Comer:");

        jLabelActivacionIrPorAgua.setText("Ir por agua:");

        jLabelActivacionBeber.setText("Beber:");

        jLabelActivacionHusmear.setText("Husmear:");

        jLabelActivacionMarcarTerritorio.setText("Marcar territorio:");

        jLabelActivacionEvacuar.setText("Evacuar:");

        jLabelActivacionirADormir.setText("Ir a dormir:");

        jLabelActivacionDormir.setText("Dormir:");

        jLabelActivacionLadrar.setText("Ladrar:");

        jLabelActivacionPelear.setText("Pelear:");

        jLabelActivacionHuir.setText("Huir:");

        javax.swing.GroupLayout jPanelActivacionLayout = new javax.swing.GroupLayout(jPanelActivacion);
        jPanelActivacion.setLayout(jPanelActivacionLayout);
        jPanelActivacionLayout.setHorizontalGroup(
            jPanelActivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActivacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelActivacionIrPorComida)
                    .addComponent(jLabelActivacionComer)
                    .addComponent(jLabelActivacionIrPorAgua)
                    .addComponent(jLabelActivacionBeber)
                    .addComponent(jLabelActivacionHusmear)
                    .addComponent(jLabelActivacionMarcarTerritorio)
                    .addComponent(jLabelActivacionEvacuar)
                    .addComponent(jLabelActivacionirADormir)
                    .addComponent(jLabelActivacionDormir)
                    .addComponent(jLabelActivacionLadrar)
                    .addComponent(jLabelActivacionPelear)
                    .addComponent(jLabelActivacionHuir))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanelActivacionLayout.setVerticalGroup(
            jPanelActivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActivacionLayout.createSequentialGroup()
                .addComponent(jLabelActivacionIrPorComida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionComer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionIrPorAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionBeber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionHusmear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionMarcarTerritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionEvacuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionirADormir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionDormir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionLadrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionPelear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActivacionHuir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMotivaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Fuerza de la Motivación"));

        jLabelMotivacionHambre.setText("Hambre:");

        jLabelMotivacionSed.setText("Sed:");

        jLabelMotivacionCuriosidad.setText("Curiosidad:");

        jLabelMotivacionExpansion.setText("Expansión:");

        jLabelMotivacionIncontinencia.setText("Incontinencia:");

        jLabelMotivacionCansancio.setText("Cansancio:");

        jLabelMotivacionIra.setText("Ira:");

        jLabelMotivacionMiedo.setText("Miedo:");

        javax.swing.GroupLayout jPanelMotivacionesLayout = new javax.swing.GroupLayout(jPanelMotivaciones);
        jPanelMotivaciones.setLayout(jPanelMotivacionesLayout);
        jPanelMotivacionesLayout.setHorizontalGroup(
            jPanelMotivacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotivacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMotivacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMotivacionHambre)
                    .addComponent(jLabelMotivacionSed)
                    .addComponent(jLabelMotivacionCuriosidad)
                    .addComponent(jLabelMotivacionExpansion)
                    .addComponent(jLabelMotivacionIncontinencia)
                    .addComponent(jLabelMotivacionCansancio)
                    .addComponent(jLabelMotivacionIra)
                    .addComponent(jLabelMotivacionMiedo))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelMotivacionesLayout.setVerticalGroup(
            jPanelMotivacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotivacionesLayout.createSequentialGroup()
                .addComponent(jLabelMotivacionHambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionSed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionCuriosidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionExpansion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionIncontinencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionCansancio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionIra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMotivacionMiedo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        // Se agrega el mundo al layout creado en NetBeans
        mundo = new Mundo();
        javax.swing.GroupLayout jPanelMundoLayout = new javax.swing.GroupLayout(jPanelMundo);
        jPanelMundo.setLayout(jPanelMundoLayout);
        jPanelMundoLayout.setHorizontalGroup(
            jPanelMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mundo,javax.swing.GroupLayout.Alignment.LEADING,40,799,800)
        );
        jPanelMundoLayout.setVerticalGroup(
            jPanelMundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mundo,javax.swing.GroupLayout.Alignment.LEADING,40,599,600)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCrearAnimat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMatarAnimat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPonerAlimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitarAlimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPonerAgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitarAgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarAnimat))
                    .addComponent(jPanelMundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMotivaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelActivacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSensores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelActivacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelMotivaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCrearAnimat)
                            .addComponent(jButtonMatarAnimat)
                            .addComponent(jButtonPonerAlimento)
                            .addComponent(jButtonQuitarAlimento)
                            .addComponent(jButtonPonerAgua)
                            .addComponent(jButtonQuitarAgua)
                            .addComponent(jButtonMostrarAnimat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelMundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        
        mundo.init();   // Se agregan estas líneas para poder iniciar el mundo
        mundo.start();
        pack();
        mundo.getVentana(this);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearAnimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAnimatActionPerformed
    	mundo.setCrearAnimat();
    }//GEN-LAST:event_jButtonCrearAnimatActionPerformed

    private void jButtonMatarAnimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatarAnimatActionPerformed
        mundo.setMatarAnimat();
    }//GEN-LAST:event_jButtonMatarAnimatActionPerformed

    private void jButtonPonerAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPonerAlimentoActionPerformed
        mundo.setCrearPlatoComida();
    }//GEN-LAST:event_jButtonPonerAlimentoActionPerformed

    private void jButtonQuitarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarAlimentoActionPerformed
    	mundo.setQuitarPlatoComida();
    }//GEN-LAST:event_jButtonQuitarAlimentoActionPerformed

    private void jButtonPonerAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPonerAguaActionPerformed
        mundo.setCrearPlatoAgua();
    }//GEN-LAST:event_jButtonPonerAguaActionPerformed

    private void jButtonQuitarAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarAguaActionPerformed
    	mundo.setQuitarPlatoAgua();
    }//GEN-LAST:event_jButtonQuitarAguaActionPerformed

    private void jButtonMostrarAnimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarAnimatActionPerformed
        mundo.setMonitorearAnimat();
    }//GEN-LAST:event_jButtonMostrarAnimatActionPerformed
    
    public void EscribeActivacionBeber(double Act) {
    	jLabelActivacionBeber.setText("Beber: " + Act);
    }
    
    public void EscribeActivacionIrPorAgua(double Act) {
    	jLabelActivacionIrPorAgua.setText("Ir por agua: " + Act);
    }
    
    public void EscribeActivacionComer (double Act) {
    	jLabelActivacionComer.setText("Comer: " + Act);
    }
    
    public void EscribeActivacionIrPorComida (double Act) {
    	jLabelActivacionIrPorComida.setText("Ir por comida: " + Act);
    }
    
    public void EscribeActivacionLadrar(double Act) {
    	jLabelActivacionLadrar.setText("Ladrar: " + Act);
    }
    
    public void EscribeActivacionPelear(double Act) {
    	jLabelActivacionPelear.setText("Pelear: " + Act);
    }
    
    public void EscribeActivacionHuir(double Act) {
    	jLabelActivacionHuir.setText("Huir: " + Act);
    }
    
    public void EscribeMotivacionHambre(double Act) {
    	jLabelMotivacionHambre.setText("Hambre: " + Act);
    }
    
    public void EscribeMotivacionSed(double Act) {
    	jLabelMotivacionSed.setText("Sed: " + Act);
    }
    
    public void EscribeMotivacionIra(double Act) {
    	jLabelMotivacionIra.setText("Ira: " + Act);
    }
    
    public void EscribeMotivacionMiedo(double Act) {
    	jLabelMotivacionMiedo.setText("Miedo: " + Act);
    }
    
    public void EscribeSensoresAguaAlAlcance(boolean Act) {
    	if (Act) jLabelSensorAgua.setText("Agua al alcance: si");
    	else jLabelSensorAgua.setText("Agua al alcance: no");
    }
    
    public void EscribeSensoresComidaAlAlcance(boolean Act) {
    	if (Act) jLabelSensorAlimento.setText("Alimento al alcance: si");
    	else jLabelSensorAlimento.setText("Alimento al alcance: no");
    }
    
    public void EscribeSensoresPerro(boolean Act) {
    	if (Act) jLabelSensorPerro.setText("Perro al alcance: si");
    	else jLabelSensorPerro.setText("Perro al alcance: no");
    }
    
    public void EscribeSensoresAgresion(boolean Act) {
    	if (Act) jLabelSensorAgresion.setText("Agresion: si");
    	else jLabelSensorAgresion.setText("Agresion: no");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfase().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearAnimat;
    private javax.swing.JButton jButtonMatarAnimat;
    private javax.swing.JButton jButtonMostrarAnimat;
    private javax.swing.JButton jButtonPonerAgua;
    private javax.swing.JButton jButtonPonerAlimento;
    private javax.swing.JButton jButtonQuitarAgua;
    private javax.swing.JButton jButtonQuitarAlimento;
    private javax.swing.JLabel jLabelActivacionBeber;
    private javax.swing.JLabel jLabelActivacionComer;
    private javax.swing.JLabel jLabelActivacionDormir;
    private javax.swing.JLabel jLabelActivacionEvacuar;
    private javax.swing.JLabel jLabelActivacionHuir;
    private javax.swing.JLabel jLabelActivacionHusmear;
    private javax.swing.JLabel jLabelActivacionIrPorAgua;
    private javax.swing.JLabel jLabelActivacionIrPorComida;
    private javax.swing.JLabel jLabelActivacionLadrar;
    private javax.swing.JLabel jLabelActivacionMarcarTerritorio;
    private javax.swing.JLabel jLabelActivacionPelear;
    private javax.swing.JLabel jLabelActivacionirADormir;
    private javax.swing.JLabel jLabelMotivacionCansancio;
    private javax.swing.JLabel jLabelMotivacionCuriosidad;
    private javax.swing.JLabel jLabelMotivacionExpansion;
    private javax.swing.JLabel jLabelMotivacionHambre;
    private javax.swing.JLabel jLabelMotivacionIncontinencia;
    private javax.swing.JLabel jLabelMotivacionIra;
    private javax.swing.JLabel jLabelMotivacionMiedo;
    private javax.swing.JLabel jLabelMotivacionSed;
    private javax.swing.JLabel jLabelSensorAgresion;
    private javax.swing.JLabel jLabelSensorAgua;
    private javax.swing.JLabel jLabelSensorAlimento;
    private javax.swing.JLabel jLabelSensorAlmohada;
    private javax.swing.JLabel jLabelSensorPerro;
    private javax.swing.JLabel jLabelSensorTerritorio;
    private javax.swing.JPanel jPanelActivacion;
    private javax.swing.JPanel jPanelMotivaciones;
    private javax.swing.JPanel jPanelMundo;
    private javax.swing.JPanel jPanelSensores;
    // End of variables declaration//GEN-END:variables
    
    // Otras variables
    Mundo mundo;
    final static long serialVersionUID = 0;
    
}